-- MySQL Script generated by MySQL Workbench
-- mié 14 nov 2018 09:10:10 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`VIVERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVERO` (
  `coordenadas` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NULL,
  PRIMARY KEY (`coordenadas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `nombre` VARCHAR(45) NOT NULL,
  `coorden_v` VARCHAR(45) NULL,
  `productividad` VARCHAR(45) NULL,
  PRIMARY KEY (`nombre`),
  INDEX `coorden_v_idx` (`coorden_v` ASC),
  CONSTRAINT `coorden_v`
    FOREIGN KEY (`coorden_v`)
    REFERENCES `mydb`.`VIVERO` (`coordenadas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO` (
  `cod_producto` INT NOT NULL,
  `stock` INT NULL,
  `precio` FLOAT NULL,
  PRIMARY KEY (`cod_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO_ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO_ZONA` (
  `cod_producto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `coorden_v` VARCHAR(45) NULL,
  `fecha` TIMESTAMP(10) NULL,
  PRIMARY KEY (`cod_producto`),
  INDEX `nombre_idx` (`nombre` ASC),
  INDEX `coorden_v_idx` (`coorden_v` ASC),
  CONSTRAINT `cod_producto`
    FOREIGN KEY (`cod_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`cod_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nombre`
    FOREIGN KEY (`nombre`)
    REFERENCES `mydb`.`ZONA` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `coorden_v`
    FOREIGN KEY (`coorden_v`)
    REFERENCES `mydb`.`ZONA` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `dni` VARCHAR(9) NOT NULL,
  `fecha_ini` TIMESTAMP(20) NOT NULL,
  `css` VARCHAR(45) NULL,
  `antigüedad` VARCHAR(45) NULL,
  `sueldo` FLOAT NULL,
  `nombre` VARCHAR(45) NULL,
  `coord` VARCHAR(45) NULL,
  `fecha_fin` TIMESTAMP(20) NULL,
  `ventas` VARCHAR(45) NULL,
  PRIMARY KEY (`dni`, `fecha_ini`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `dni` VARCHAR(9) NOT NULL,
  `total_mens` FLOAT NULL,
  `bonificacion` FLOAT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE_PROD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE_PROD` (
  `dni_c` VARCHAR(9) NOT NULL,
  `dni_e` VARCHAR(9) NOT NULL,
  `cod_producto` INT NOT NULL,
  `fecha` TIMESTAMP(20) NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`dni_c`, `dni_e`, `cod_producto`, `fecha`),
  INDEX `dni_e_idx` (`dni_e` ASC),
  INDEX `cod_producto_idx` (`cod_producto` ASC),
  CONSTRAINT `dni_c`
    FOREIGN KEY (`dni_c`)
    REFERENCES `mydb`.`CLIENTE` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `dni_e`
    FOREIGN KEY (`dni_e`)
    REFERENCES `mydb`.`EMPLEADO` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_producto`
    FOREIGN KEY (`cod_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`cod_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
